version: '3.8'

services:
  tandb:
    image: mysql:8.0
    container_name: tandbc1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb

  tanflaskwebapp:
    image: tanflask:webappv1
    build: . #location of dockerfile and . means current location
    ports:
      - "3030:5000"
    environment:
      FLASK_ENV: development
      MYSQL_HOST: tandb #db server name
      MYSQL_USER: root # db user name
      MYSQL_PASSWORD: example # db user password
      MYSQL_DATABASE: testdb
    depends_on:
      - tandb
